notes: |
  Push an element to the right if the space allows it, otherwise display it below.
status: wip
variants:
  - name: middle
    notes: Vertically align content in the middle.
    context:
      modifier: pusher--middle
  - name: bottom
    notes: Vertically align content to the bottom.
    context:
      modifier: pusher--bottom
